workflows:
  simpleweb-ios:
    name: SimpleWeb iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - xcodebuild -list -project SimpleWeb.xcodeproj
      - xcodebuild -project SimpleWeb.xcodeproj -scheme SimpleWeb -sdk iphoneos -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - you@email.com
