workflows:
  simpleweb-ios:
    name: SimpleWeb iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - xcodebuild -project SimpleWeb.xcodeproj -target SimpleWeb -sdk iphonesimulator -configuration Debug build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO 2>&1
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - you@email.com
