name: SimpleWeb
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "10.0"
  xcodeVersion: "15.0"
  generateSchemes:
    SimpleWeb:
      parallelizeBuild: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "2"

targets:
  SimpleWeb:
    type: application
    platform: iOS
    sources:
      - path: SimpleWeb
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.simpleweb
        INFOPLIST_FILE: SimpleWeb/Info.plist
        DEVELOPMENT_TEAM: ""
